### ISSUE TITLE
"Customize transaction" flow on SEND is providing bad PSBT for hardwallets using published APK on ungoogled phone

### ISSUE THREAD

**Issue by bitcoinheiro** [nunchuk-io/nunchuk-android#25]
When using the "Create transaction" button, all works fine and I can see the singlesig hardwallet to sign - and it works as expected!
But when I go through the "Customize transaction" flow, it does not show the correct device to sign and if I export as QR from above it is lacking information for the device to proceed with signing flow.

Please see screenshot below:
This is how it should be, with keys below to sign:
![image](https://github.com/nunchuk-io/nunchuk-android/assets/50273260/5cc1fffb-5f53-4cfe-8ff9-d2e9ea6e33ca)

This is the customize transaction I'm talking about:
![image](https://github.com/nunchuk-io/nunchuk-android/assets/50273260/38926b4b-af33-4492-b691-a61d17d83449)

This is how it looks after customizing fees:
![image](https://github.com/nunchuk-io/nunchuk-android/assets/50273260/2d76c08a-a318-47c4-9fc8-a42b055f58e6)

Where is the key? Without the button on the key to sign, by signing using the general menu, the hardwallet fails to identify the policy:
![image](https://github.com/nunchuk-io/nunchuk-android/assets/50273260/319a14e4-8bf3-4e72-846b-17eb5de96195)

**Comment by hugohn** [comment]
Hey @bitcoinheiro, about this transaction, did you send BTC back to your own wallet? If so, only the change amount is relevant for the wallet and updating the wallet balance. The rest is subtracted as it goes to the miners.

**Comment by bitcoinheiro** [comment]
No, I was not sending BTC to the own wallet. The transaction I was trying to make had 1 input and 2 outputs (1 external + 1 change). When using the "Create transaction" button, all worked as expected. But after the "Customize transaction" flow, it prioritized the change output for some reason (bigger than spend??)

**Comment by bitcoinheiro** [comment]
I've tried making a transaction where the spend output was bigger than the change one to check my theory above, but no success. Will post a video to help you reproduce the bug.

You can see my video showing where/how the bug happens here:
https://youtu.be/bIDedEGDJxg

**Comment by hugohn** [comment]
@bitcoinheiro we have many users who connect to their own node over Tor, so that's not an issue. Anyway, we'll investigate it.

**Comment by bitcoinheiro** [comment]
> @bitcoinheiro are you using our published APK on GrapheneOS? Or did you compile from source?

Yes, so this is Play Services related?

**Comment by hugohn** [comment]
@bitcoinheiro the APK is NOT different from the source. The reason I'm asking is whether your build environment/compilation process might have caused a bug, especially how you compiled the SDK.

**Comment by bitcoinlizard** [comment]
I'm seeing a similar issue to what @bitcoinheiro is seeing.  

I am using APK version 1.9.32 (1.9.31 was also affected) on a phone running GrapheneOS with no Google Play Services installed.  I created a new single sig wallet with a ColdCard for the signing key.  I am trying to "send all".  I scan a QR of the receiving address (an address outside of the nunchuk wallet).  If I click "Create transaction" I receive an insufficient funds error because there is no money to pay the miner fee.  If I click "Customize transaction" I immediately see the same error message for insufficient funds.  I check the box for "Subtract fee from send amount" and click "Continue".  Everything looks good at the next screen.  I then click "Confirm and create transaction".  I am at the "Pending Signatures" screen and the "Receive at" doesn't show an address and the amount is zero.

I recreated the exact same wallet in the iOS version of the app.  Everything works correctly without issue.  One thing I noticed was that the "Subtract fee from send amount" seems to be a default option in the iOS version of the app but not the Android APK.

**Comment by JayceLuong** [comment]
Could you use this version and help us verify that it works? We cannot reproduce on our side. This is new APK https://drive.google.com/file/d/1Zw275m64vPej04UXjXIF7cFnG2PX9Bhu/view?usp=sharing

**Comment by bitcoinlizard** [comment]
Thank you @JayceLuong.  This version seems to have solved the issue.  I can see that "Subtract fee from send amount" is now enabled by default.  I don't have access to my signing key at the moment to complete the transaction but it would appear that my issue is resolved.
