### ISSUE TITLE
Impossible to sweep an unsealed satscard slot

### ISSUE THREAD

**Issue by iujzvbc** [nunchuk-io/nunchuk-android#47]
When I try to sweep balance of an unsealed satscard slot either to the nunchuk hot wallet or a regular bitcoin address, I get this red message and nothing happens then:
-1013:Daemon error: DaemonError({'code': -5, 'message': 'No such mempool or blockchain transaction. Use gettransaction for wallet transactions.'})
Pixel 6a with GrapheneOS up to date
Nunchuk 1.9.41 from playstore or 1.9.40 from f-droid show the same error.
Cannot share the logs in dev mode because the log file is empty.

**Comment by kirkawolff** [comment]
Same. On grapheneOS pixel6 after failed attempt to sweep, then a second attempt to sweep unsealed slot, i get a red toast with the following error:
```
[json.exception.type_error.305] cannot use operator [] with a string argument with string
```

**Comment by giahuy98** [comment]
Hello @kirkawolff,
Did you use default Nunchuk node or your own node to sweep the Satscard?

**Comment by kirkawolff** [comment]
You mean the one printed on the card? Yes it was the first slot

**Comment by kirkawolff** [comment]
I tried both, same results

**Comment by giahuy98** [comment]
After failing to sweep and scanning it again, did your Satscard unseal the current slot and require you to set up a new slot? Also, what version is printed on the back of your Satscard?

**Comment by kirkawolff** [comment]
Yes, but i declined to set up a new slot and asked to sweep an unsealed slot.

It is v1.0.3

![IMG_20240620_100756.jpg](https://github.com/nunchuk-io/nunchuk-android/assets/13596099/9285c763-8e6b-440d-990d-a7277d3ee2e7)

**Comment by giahuy98** [comment]
The error `[json.exception.type_error.305] cannot use operator [] with a string argument` occurs when your Satscard has many UTXOs and your node refuses to provide them. Blockstream electrs or an old version of romanz/electrs will give the error `Too many history entries` in this case.

The error `-1013: Daemon error: DaemonError({'code': -5, 'message': 'No such mempool or blockchain transaction. Use gettransaction for wallet transactions.'})` come from ElectrumX/bitcoind is probably because the node you connected to is out of sync. You may need to run bitcoind with the -reindex option. It will be our responsibility if that is a Nunchuk node that you connected to :)

I suggest you switch to another node (Fulcrum or ElectrumX) and try to sweep again. `ssl://electrum.bitaroo.net:50002` is probably a good choice.

I will work on some optimizations for fetching UTXOs in the meantime.

**Comment by kirkawolff** [comment]
Thanks!
I tried both my local electrs and mainnet.nunchuk.io:51001. Ill try this one and let you know what happens.

**Comment by kirkawolff** [comment]
Thanks!
I tried both my local electrs and mainnet.nunchuk.io:51001.

I switched to bitaroo and this is the error i get.

![IMG_20240621_095756.jpg](https://github.com/nunchuk-io/nunchuk-android/assets/13596099/78289e6b-2832-45ed-a399-afdd296d8e53)

**Comment by giahuy98** [comment]
Let's try another Fulcrum node: `ssl://fulcrum.sethforprivacy.com:50002`
Also, could you try this apk: https://drive.google.com/file/d/1hqMMy-8TL4ZA_KI1z5baIlDLopk7svpg/view?usp=sharing

**Comment by kirkawolff** [comment]
What is the apk for?

**Comment by giahuy98** [comment]
I did a couple of optimizations and improved the error messages when sweeping Satscard.
If you want a signed APK, we can push it to GitHub.

**Comment by kirkawolff** [comment]
I will need it to be signed or ill lose my other configs and i dont have an extra phone already set up

**Comment by kirkawolff** [comment]
I get the same error with the seth for privacy electrum server

![IMG_20240621_095756.jpg](https://github.com/nunchuk-io/nunchuk-android/assets/13596099/78289e6b-2832-45ed-a399-afdd296d8e53)

**Comment by giahuy98** [comment]
The apk is here @kirkawolff. Please give it a try.
https://github.com/nunchuk-io/nunchuk-android/releases/tag/android.1.9.47

**Comment by kirkawolff** [comment]
I tried the following combinations with this prerelease

Satscard with single uxto using fulcrum: success

Satscard with multiple uxtos using private electrs: success

Whatever changes you made to this version fixed it. I can't find the branch containing your changes so i have no idea what you did.

**Comment by giahuy98** [comment]
We will publish the code changes and release an official fix version soon, ETA ~1 week. 
The bug was a UTXO mapping error between Nunchuk Android app and libnunchuk, leading to an all-zero txid, which is why Electrum server returned the error 'No such mempool or blockchain transaction...'. 

Thank you for your help in identifying and fixing this issue.
